### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by MahyarFardin** [Omid-Nejati/MedViT#15]
Hi Omid,
While I try to run your code with this instruction https://colab.research.google.com/github/Omid-Nejati/MedViT/blob/main/Colab_MedViT.ipynb, I repeatedly confront 
"
CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
"
this error. Would you mind helping me through this problem?
BTW, I am running on colab so I have a T4 GPU.

**Comment by Omid-Nejati** [comment]
Hi Mahyar,

I strongly recommend checking out the new version of the code available at [this link](https://github.com/Omid-Nejati/MedViT/blob/main/Instructions.ipynb).

In the meantime, an error sometimes occurs due to a mismatch between the classifier output and the number of dataset classes. Please verify the following lines in your code:

n_classes = len(info['label'])
model.proj_head[0] = torch.nn.Linear(in_features=1024, out_features=2, bias=True)
Ensure that out_features is equal to n_classes.
